# Breast Cancer Example
## Training Notebook
This notebook trains the model. The first cell imports everything needed. The second cell is where you pass in your arguments. The third cell runs the model training. Lastly, the fourth cell is there if you wish to continue training a certain model.

In [1]:
import os
import sys

# Import keras3_tools from proper path
neuro_path = os.getenv("NEURO_REPOSITORY_PATH")
assert neuro_path is not None, "Environment variable NEURO_REPOSITORY_PATH must be set to directory above zero2neuro and keras3_tools"

sys.path.append(neuro_path + '/zero2neuro/src/')

from zero2neuro import *
from parser import *

2025-07-25 14:06:04.847188: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-07-25 14:06:04.868489: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


## Parser
This is the argument parser. Inside of the parse_args function you can put in the arguments you want that are listed in the zero2neuro/src/parser.py file. The default set in this notebooks is as follows. 

@network.txt - Passes in the network file for iris  
@data.txt - Passes in the data file for Iris  
@experiment.txt - Passes in the experiment file for iris  
**-v** - Handles the verbosity level, in this case it is low.    
**--force** - Will overwrite a previous model with the same name with the new one.  
**--log_training_set** - Puts the training set in the pickle file  
**--log_validation_set** - Puts the validation set in the pickle file  
**--log_test_set** - Puts the testing set in the pickle file  

In [2]:
parser = create_parser()
args = parser.parse_args(["@network_config.txt", "@data_config.txt", "@experiment_config.txt", "-v",
                          "--force", "--log_training_set", '--log_validation_set','--log_test_set', '-d'])
print(args)

Namespace(experiment_name='breast_cancer', loss='binary_crossentropy', metrics=['binary_accuracy'], rotation=None, epochs=5000, learning_rate=0.0001, clipnorm=None, results_path='./results', output_file_base='{args.experiment_name}_R{args.data_rotation:02d}', early_stopping=False, early_stopping_min_delta=0.01, early_stopping_patience=2000, early_stopping_monitor='loss', dataset_directory=None, training_mode=None, data_format='tabular', data_representation='numpy', data_split=None, data_fold_split='random', data_set_type='holistic-cross-validation', n_folds=None, n_training_folds=None, data_n_folds=10, data_n_training_folds=None, data_rotation=1, data_file='wdbc.csv', data_files=None, data_inputs=['radius1', 'texture1', 'area1', 'smoothness1', 'compactness1', 'concavity1', 'concave_points1', 'symmetry1', 'fractal_dimension1', 'rasius2', 'texture2', 'perimeter2', 'area2', 'smoothness2', 'compactness2', 'concavity2', 'concave_points2', 'symmetry2', 'fractal_dimension2', 'radius3', 'textu

In [3]:
prepare_and_execute_experiment(args)

NO VISIBLE DEVICES!!!!
GPUS: []
NO GPU
CSV file
############# 1
TOTAL DATA FILES: 1
#############
############# 1
TOTAL DATA FOLDS: 10
#############
./results/breast_cancer_R01
Fitting model
!!!!!!!!!!!!!!!!!!
TRAINING:
[[1.846e+01 1.852e+01 1.075e+03 ... 1.642e-01 3.695e-01 8.579e-02]
 [9.465e+00 2.101e+01 2.694e+02 ... 6.517e-02 2.878e-01 9.211e-02]
 [1.882e+01 2.197e+01 1.110e+03 ... 1.708e-01 3.007e-01 8.314e-02]
 ...
 [1.286e+01 1.800e+01 5.063e+02 ... 7.926e-02 2.779e-01 7.918e-02]
 [1.298e+01 1.935e+01 5.140e+02 ... 9.858e-02 3.596e-01 9.166e-02]
 [2.109e+01 2.657e+01 1.311e+03 ... 2.903e-01 4.098e-01 1.284e-01]]
[[1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [

In [ ]:
# Load model and dataset and redo experiment 
model = keras.models.load_model('results/breast_cancer_R00_model.keras')
sds = SuperDataSet(args)
execute_exp(sds, model, args)