# Amino Acid Example
## Training Notebook


In [1]:
%reload_ext autoreload
%autoreload 2

In [14]:
import os
import sys

# Import keras3_tools from proper path
neuro_path = os.getenv("NEURO_REPOSITORY_PATH")
assert neuro_path is not None, "Environment variable NEURO_REPOSITORY_PATH must be set to directory above zero2neuro and keras3_tools"

sys.path.append(neuro_path + '/zero2neuro/src/')

from zero2neuro import *
from parser import *

In [21]:
parser = create_parser()
args = parser.parse_args(["@data.txt", "@network.txt", "@experiment.txt", "-vvv", "-ddd"])
print(args)


Namespace(experiment_name='amino_acid', loss='mse', metrics=['mae', 'mse'], rotation=None, epochs=1000, learning_rate=0.001, clipnorm=None, results_path='./results', output_file_base='{args.experiment_name}_R{args.data_rotation:02d}', early_stopping=True, early_stopping_min_delta=0.01, early_stopping_patience=100, early_stopping_monitor='loss', dataset_directory=None, training_mode=None, data_format='tabular', data_representation='numpy', data_split=None, data_fold_split='random', data_set_type='holistic-cross-validation', n_folds=None, n_training_folds=None, data_n_folds=10, data_n_training_folds=None, data_n_validation_folds=1, data_rotation=0, data_file='train_1501_fold1.csv', data_files=None, data_inputs=['string'], data_outputs=['binding'], data_weights=None, data_groups=None, data_stratify=None, tabular_header_row=None, tabular_header_names=['string', 'binding'], tabular_column_range=None, tabular_column_list=None, data_output_sparse_categorical=False, data_columns_categorical_to

In [22]:
print(args.network_type)

fully_connected


In [ ]:
prepare_and_execute_experiment(args)

In [7]:
# Load model and dataset and redo experiment 
#xor_model = keras.models.load_model('results/xor_R01_model.keras')
#sds = SuperDataSet(args)
#execute_exp(sds, xor_model, args)

In [23]:
sds = SuperDataSet(args)

CSV file
############# 1
TOTAL DATA FILES: 1
#############
############# 1
TOTAL DATA FOLDS: 10
#############
VF:1
############# 2
TRAINING FOLDS: [0 1 2 3 4 5 6 7]
#############
############# 2
VALIDATION FOLDS: [8]
#############
############# 2
TESTING FOLD: 9
#############
<dtype: 'string'>
(3133, 1)
tf.Tensor(
[[b'EMPSEEGYQDYEPEA']
 [b'VCKHTYVDRGWGNGC']
 [b'LFLHLVGFPTHRHIQ']
 ...
 [b'RDHYILYCEGELHGRQ']
 [b'NELQIVDKIDAAFKI']
 [b'GETQIVDKIDAAFKI']], shape=(3133, 1), dtype=string)


In [5]:
sds.ins_validation

<tf.Tensor: shape=(391, 1), dtype=string, numpy=
array([[b'MAVYTLITAAIIHRE'],
       [b'TARLNSLGEAWTGGG'],
       [b'ADLDSGAVIAARDPH'],
       [b'GKNERELATLHHLNP'],
       [b'ESEFQAALSRKVAKL'],
       [b'LIGLRIVFAVLSIVNRVRQG'],
       [b'PFTVRYTTEGGTKTE'],
       [b'SLILVSQYTPDSTPC'],
       [b'EAETMTPSGLVIPEN'],
       [b'LVTVNPIASTNDDEV'],
       [b'LLFCALASSCQVAFS'],
       [b'LVKPGAGIMIFDPYG'],
       [b'FAVVDLNKMRAVWVDGKART'],
       [b'AAGVPPADKYRTFVA'],
       [b'AEYKSDYVYEPFPKE'],
       [b'IPVFLQEALNIALVA'],
       [b'DPMVQIPRLVANNTR'],
       [b'GFKAALAAAAGVQPADKYRT'],
       [b'VSTFSSGLVWGQKYF'],
       [b'SKGSSSELSAQQKK'],
       [b'LVTMPIGYVTHGFNL'],
       [b'EIYKRWIILG'],
       [b'SAAVKDERAVHADMG'],
       [b'IAGYKTFDGRGAQVY'],
       [b'GNTPIFKSGRGCGSC'],
       [b'YVLSSLHIYWGKE'],
       [b'PRTKYTATISGLKPG'],
       [b'SVLLVVVLFAVFLGS'],
       [b'FIFGEARSLYLNTEL'],
       [b'DKVYEILKINSVKYY'],
       [b'GRLEYCLKDRMNFDI'],
       [b'VFNICQAVTANVNAL'],
       [b'EVFCQT

In [6]:
sds.ins_testing

<tf.Tensor: shape=(391, 1), dtype=string, numpy=
array([[b'NQEILELAQSETCSP'],
       [b'TSALIWMASPPEVHS'],
       [b'PELQNFLNFLEANGL'],
       [b'CDDALIEGITLLNAK'],
       [b'TIRVLALGNQEGSLK'],
       [b'NLPLQLGFSTGVNLV'],
       [b'SRAEVSYVHVNGAKF'],
       [b'ASRELERFALNPGLL'],
       [b'TASHTRLSCDCDDKFYDC'],
       [b'AEVRSYCYLATVSDL'],
       [b'NPLIRHENRMVLAST'],
       [b'RTEQKDFDGRSEFAY'],
       [b'GELQICDKIDAAFKI'],
       [b'IAPIMFSNKMARLGK'],
       [b'KPFAEYKSDYVYEPF'],
       [b'KGQKRIKCFNCGKEGHL'],
       [b'WIESQKNGSWKLEKA'],
       [b'MGQFISFMQEIPTFL'],
       [b'GELQIVDKIDASFKI'],
       [b'PALLALLALPALLLL'],
       [b'GGITLFLGFTVQADM'],
       [b'HSLLDEGKQSLTKLA'],
       [b'EGKVVQYENLKYTVI'],
       [b'GELQIKDKIDAAFKI'],
       [b'ERFAVNPGLLETSEGCR'],
       [b'GELQIVDKIDAAFKG'],
       [b'ENPVVHAFRNIVTPR'],
       [b'FFVKNPTDTGHGTVV'],
       [b'GNGVVALRNAQLVTF'],
       [b'VENTEKALNVYYEIGKILSR'],
       [b'MSQIMYNYPAMMAHA'],
       [b'IGRIAETILGYNPSA'],
       [b'T

In [18]:
dir(sds)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'args',
 'calculate_indices',
 'calculate_nfolds',
 'categorical_feature_translation',
 'categorical_translation',
 'check_data_tables',
 'combine_all_data_tables',
 'data',
 'data_groups',
 'data_xlsx_sheet_names',
 'dataset_split_fixed',
 'dataset_type',
 'describe',
 'folds',
 'generate_datasets',
 'generate_folds',
 'generate_folds_by_example_numpy',
 'generate_folds_by_group_numpy',
 'generate_folds_by_group_tf',
 'generate_folds_random_numpy',
 'get_normalization_divisor',
 'ins_testing',
 'ins_training',
 'ins_validation',
 'is_list_of_tf_datasets',
 'is_list_of_tuples',
 'is_missing_values',
 'loa

In [24]:
sds.ins_training

array([['EMPSEEGYQDYEPEA'],
       ['VCKHTYVDRGWGNGC'],
       ['LFLHLVGFPTHRHIQ'],
       ...,
       ['RDHYILYCEGELHGRQ'],
       ['NELQIVDKIDAAFKI'],
       ['GETQIVDKIDAAFKI']], dtype=object)

In [24]:
model = NetworkBuilder.args2model(args)

INPUT SHAPE [1]


In [26]:
print(model.summary())

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ fcinput (InputLayer)            │ (None, 1)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ text_vectorization              │ (None, 50)             │             0 │
│ (TextVectorization)             │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ embedding (Embedding)           │ (None, 50, 15)         │           360 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 750)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ hidden_0 (Dense)                │ (None, 200)            │       150,200 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ hidden_1 (Dense)                │ (None, 100)            │        20,100 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ hidden_2 (Dense)                │ (None, 50)             │         5,050 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ hidden_3 (Dense)                │ (None, 25)             │         1,275 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ hidden_4 (Dense)                │ (None, 10)             │           260 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ fcoutput (Dense)                │ (None, 1)              │            11 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 177,256 (692.41 KB)

 Trainable params: 177,256 (692.41 KB)

 Non-trainable params: 0 (0.00 B)

None


In [27]:
model.fit(sds.ins_training, sds.outs_training, epochs=2)

Epoch 1/2


2026-01-26 16:26:40.928907: W tensorflow/core/framework/op_kernel.cc:1857] OP_REQUIRES failed at lookup_table_op.cc:932 : FAILED_PRECONDITION: Table not initialized.
2026-01-26 16:26:40.928936: I tensorflow/core/framework/local_rendezvous.cc:407] Local rendezvous is aborting with status: FAILED_PRECONDITION: Table not initialized.
	 [[{{function_node __inference_one_step_on_data_2513}}{{node functional_1/text_vectorization_1/None_Lookup/LookupTableFindV2}}]]


FailedPreconditionError: Graph execution error:

Detected at node functional_1/text_vectorization_1/None_Lookup/LookupTableFindV2 defined at (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main

  File "<frozen runpy>", line 88, in _run_code

  File "/home/fagg/miniconda3/envs/dnn_2025_02/lib/python3.12/site-packages/ipykernel_launcher.py", line 18, in <module>

  File "/home/fagg/miniconda3/envs/dnn_2025_02/lib/python3.12/site-packages/traitlets/config/application.py", line 1075, in launch_instance

  File "/home/fagg/miniconda3/envs/dnn_2025_02/lib/python3.12/site-packages/ipykernel/kernelapp.py", line 739, in start

  File "/home/fagg/miniconda3/envs/dnn_2025_02/lib/python3.12/site-packages/tornado/platform/asyncio.py", line 211, in start

  File "/home/fagg/miniconda3/envs/dnn_2025_02/lib/python3.12/asyncio/base_events.py", line 645, in run_forever

  File "/home/fagg/miniconda3/envs/dnn_2025_02/lib/python3.12/asyncio/base_events.py", line 1999, in _run_once

  File "/home/fagg/miniconda3/envs/dnn_2025_02/lib/python3.12/asyncio/events.py", line 88, in _run

  File "/home/fagg/miniconda3/envs/dnn_2025_02/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 516, in dispatch_queue

  File "/home/fagg/miniconda3/envs/dnn_2025_02/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 505, in process_one

  File "/home/fagg/miniconda3/envs/dnn_2025_02/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 397, in dispatch_shell

  File "/home/fagg/miniconda3/envs/dnn_2025_02/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 368, in execute_request

  File "/home/fagg/miniconda3/envs/dnn_2025_02/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 752, in execute_request

  File "/home/fagg/miniconda3/envs/dnn_2025_02/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 455, in do_execute

  File "/home/fagg/miniconda3/envs/dnn_2025_02/lib/python3.12/site-packages/ipykernel/zmqshell.py", line 577, in run_cell

  File "/home/fagg/miniconda3/envs/dnn_2025_02/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3116, in run_cell

  File "/home/fagg/miniconda3/envs/dnn_2025_02/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3171, in _run_cell

  File "/home/fagg/miniconda3/envs/dnn_2025_02/lib/python3.12/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner

  File "/home/fagg/miniconda3/envs/dnn_2025_02/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3394, in run_cell_async

  File "/home/fagg/miniconda3/envs/dnn_2025_02/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3639, in run_ast_nodes

  File "/home/fagg/miniconda3/envs/dnn_2025_02/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3699, in run_code

  File "/tmp/ipykernel_347827/845420708.py", line 1, in <module>

  File "/home/fagg/miniconda3/envs/dnn_2025_02/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py", line 117, in error_handler

  File "/home/fagg/miniconda3/envs/dnn_2025_02/lib/python3.12/site-packages/keras/src/backend/tensorflow/trainer.py", line 377, in fit

  File "/home/fagg/miniconda3/envs/dnn_2025_02/lib/python3.12/site-packages/keras/src/backend/tensorflow/trainer.py", line 220, in function

  File "/home/fagg/miniconda3/envs/dnn_2025_02/lib/python3.12/site-packages/keras/src/backend/tensorflow/trainer.py", line 133, in multi_step_on_iterator

  File "/home/fagg/miniconda3/envs/dnn_2025_02/lib/python3.12/site-packages/keras/src/backend/tensorflow/trainer.py", line 114, in one_step_on_data

  File "/home/fagg/miniconda3/envs/dnn_2025_02/lib/python3.12/site-packages/keras/src/backend/tensorflow/trainer.py", line 58, in train_step

  File "/home/fagg/miniconda3/envs/dnn_2025_02/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py", line 117, in error_handler

  File "/home/fagg/miniconda3/envs/dnn_2025_02/lib/python3.12/site-packages/keras/src/layers/layer.py", line 936, in __call__

  File "/home/fagg/miniconda3/envs/dnn_2025_02/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py", line 117, in error_handler

  File "/home/fagg/miniconda3/envs/dnn_2025_02/lib/python3.12/site-packages/keras/src/ops/operation.py", line 58, in __call__

  File "/home/fagg/miniconda3/envs/dnn_2025_02/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py", line 156, in error_handler

  File "/home/fagg/miniconda3/envs/dnn_2025_02/lib/python3.12/site-packages/keras/src/models/functional.py", line 183, in call

  File "/home/fagg/miniconda3/envs/dnn_2025_02/lib/python3.12/site-packages/keras/src/ops/function.py", line 177, in _run_through_graph

  File "/home/fagg/miniconda3/envs/dnn_2025_02/lib/python3.12/site-packages/keras/src/models/functional.py", line 648, in call

  File "/home/fagg/miniconda3/envs/dnn_2025_02/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py", line 117, in error_handler

  File "/home/fagg/miniconda3/envs/dnn_2025_02/lib/python3.12/site-packages/keras/src/layers/layer.py", line 936, in __call__

  File "/home/fagg/miniconda3/envs/dnn_2025_02/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py", line 117, in error_handler

  File "/home/fagg/miniconda3/envs/dnn_2025_02/lib/python3.12/site-packages/keras/src/ops/operation.py", line 58, in __call__

  File "/home/fagg/miniconda3/envs/dnn_2025_02/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py", line 156, in error_handler

  File "/home/fagg/miniconda3/envs/dnn_2025_02/lib/python3.12/site-packages/keras/src/layers/preprocessing/text_vectorization.py", line 580, in call

  File "/home/fagg/miniconda3/envs/dnn_2025_02/lib/python3.12/site-packages/keras/src/layers/preprocessing/string_lookup.py", line 391, in call

  File "/home/fagg/miniconda3/envs/dnn_2025_02/lib/python3.12/site-packages/keras/src/layers/preprocessing/index_lookup.py", line 716, in call

  File "/home/fagg/miniconda3/envs/dnn_2025_02/lib/python3.12/site-packages/keras/src/layers/preprocessing/index_lookup.py", line 766, in _lookup_dense

Table not initialized.
	 [[{{node functional_1/text_vectorization_1/None_Lookup/LookupTableFindV2}}]] [Op:__inference_multi_step_on_iterator_2621]